-- RDB Join Lab: coupon domain schema, PostgreSQL arm.
-- Mirrors db/schema.sql (MySQL). 3NF; NO foreign key constraints intentionally:
-- the "ID direct-reference" design enforces referential integrity at the
-- application layer, and that design is the thing being benchmarked.
--
-- Parity notes:
--   AUTO_INCREMENT        -> GENERATED BY DEFAULT AS IDENTITY (seeder inserts
--                            explicit ids; BY DEFAULT permits that; seed-pg.sh
--                            resets the sequence afterwards)
--   DATETIME              -> timestamp (without time zone), as Hibernate maps
--                            LocalDateTime identically on both engines
--   ENGINE/CHARSET        -> not applicable
-- Index set is identical, including the R4 composite (member_id, id) that
-- removes the sort from Scenario B's ORDER BY id queries.

CREATE EXTENSION IF NOT EXISTS pg_prewarm;

CREATE TABLE IF NOT EXISTS coupon_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(100) NOT NULL,
    type            VARCHAR(20)  NOT NULL,
    discount_amount INT          NOT NULL,
    expire_at       TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS member (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(50)  NOT NULL,
    email      VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    PRIMARY KEY (id)
);

-- coupon_issue joins policy and member via scalar id columns (no FK).
-- Two separate entity mappings exist in the app:
--   CouponIssue  (association-mapped: @ManyToOne policy, @ManyToOne member)
--   CouponIssueRef (id-ref read model: scalar policyId, memberId; @Immutable)
CREATE TABLE IF NOT EXISTS coupon_issue (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    policy_id  BIGINT      NOT NULL,
    member_id  BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL,  -- ISSUED | USED | EXPIRED
    issued_at  TIMESTAMP   NOT NULL,
    used_at    TIMESTAMP   NULL,
    PRIMARY KEY (id)
);

-- Secondary indexes (realistic read patterns), same set as MySQL.
CREATE INDEX IF NOT EXISTS idx_issue_member_status
    ON coupon_issue (member_id, status);

-- R4 fix: composite index (member_id, id) so WHERE member_id = ? ORDER BY id ASC
-- is satisfied by a single index scan with no Sort node (the PG analogue of
-- MySQL's filesort elimination).
CREATE INDEX IF NOT EXISTS idx_issue_member_id
    ON coupon_issue (member_id, id);

CREATE INDEX IF NOT EXISTS idx_issue_policy_issued
    ON coupon_issue (policy_id, issued_at);

CREATE INDEX IF NOT EXISTS idx_policy_expire
    ON coupon_policy (expire_at);

-- Scenario C: status-scan indexes, same rationale as MySQL.
CREATE INDEX IF NOT EXISTS idx_issue_status
    ON coupon_issue (status);

CREATE INDEX IF NOT EXISTS idx_issue_status_policy
    ON coupon_issue (status, policy_id, issued_at);
