#!/usr/bin/env python3
"""figures.py — emit pgfplots figures + data from the judged measurement data.

Academic LaTeX papers render figures with pgfplots/TikZ (vector, compiles inline, no
matplotlib/gnuplot needed). This script reuses judge.py's aggregation and writes, into
paper/figures/:
  - <fig>.dat   : whitespace-separated data tables consumed by pgfplots
  - figures.tex : the pgfplots axis environments (\\input from the paper)

Re-run unchanged on the merged coarse+precision set once precision-final.csv lands; the
scripts are the durable artifact, the data they read gets refreshed.

    python3 analysis/figures.py [csv ...]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import judge  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "..", "ops", "projects", "rdb-join-paper", "paper", "figures")


def series_b(agg, style, rtt, ns):
    """(N, p50, valid) rows for a scenario-b style at one RTT, over the N grid."""
    out = []
    for n in ns:
        c = judge.get(agg, "b", style, rtt, n)
        if c and c["p50"] is not None:
            out.append((n, c["p50"], 1 if c["valid"] else 0))
    return out


def write_dat(name, header, rows):
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        f.write("# " + header + "\n")
        for r in rows:
            f.write(" ".join(str(x) for x in r) + "\n")
    return name


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv", nargs="*", default=["analysis/coarse-final-Nrecovered.csv"])
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    rows = judge.load(args.csv)
    agg = judge.aggregate(rows)
    NS = [20, 100, 300, 500, 1000]
    DBN = judge.DISTINCT_BY_N

    tex = [r"% Auto-generated by analysis/figures.py. Do not edit by hand.",
           r"% Requires \usepackage{pgfplots}\pgfplotsset{compat=1.16} in the preamble.", ""]

    # --- Fig 1: pool-saturation cliff at cross-AZ RTT (1500us), p50 (log) vs N ---
    for st in ("joinfetch", "inbatch", "lazy", "byid"):
        write_dat(f"cliff-{st}.dat", f"N p50_ms valid (scenario b, rtt1500, {st})",
                  series_b(agg, st, 1500, NS))
    tex += [
        r"\begin{figure}[t]\centering",
        r"\begin{tikzpicture}\begin{semilogyaxis}[width=\columnwidth,height=5cm,",
        r"  xlabel={Result-set size $N$},ylabel={p50 latency (ms)},",
        r"  legend pos=north west,legend style={font=\footnotesize},xmin=0,grid=both]",
        r"\addplot table[x index=0,y index=1] {figures/cliff-joinfetch.dat};\addlegendentry{joinfetch (flat)}",
        r"\addplot table[x index=0,y index=1] {figures/cliff-inbatch.dat};\addlegendentry{inbatch (flat)}",
        r"\addplot table[x index=0,y index=1] {figures/cliff-lazy.dat};\addlegendentry{lazy (N+1)}",
        r"\addplot table[x index=0,y index=1] {figures/cliff-byid.dat};\addlegendentry{byid (N+1)}",
        r"\end{semilogyaxis}\end{tikzpicture}",
        r"\caption{Pool-saturation cliff at nominal RTT $1{,}500\,\mu$s (cross-AZ), $\lambda=20$ req/s, "
        r"pool $=10$. N+1 styles (lazy, byid) climb linearly to $N=100$ then collapse into pool "
        r"saturation by $N=300$; flat styles stay bounded. Coarse sweep (preliminary).}",
        r"\label{fig:cliff}\end{figure}", ""]

    # --- Fig 2: lazy vs byid overlap (mapping-philosophy invisible by construction) at rtt300 ---
    for st in ("lazy", "byid"):
        write_dat(f"overlap-{st}.dat", f"N p50_ms (scenario b, rtt300, {st})",
                  [(n, p, v) for n, p, v in series_b(agg, st, 300, NS) if v])
    tex += [
        r"\begin{figure}[t]\centering",
        r"\begin{tikzpicture}\begin{axis}[width=\columnwidth,height=5cm,",
        r"  xlabel={Result-set size $N$},ylabel={p50 latency (ms)},legend pos=north west,",
        r"  legend style={font=\footnotesize},grid=both]",
        r"\addplot table[x index=0,y index=1] {figures/overlap-lazy.dat};\addlegendentry{lazy (assoc-mapped N+1)}",
        r"\addplot[mark=o,only marks] table[x index=0,y index=1] {figures/overlap-byid.dat};\addlegendentry{byid (ID-ref N+1)}",
        r"\end{axis}\end{tikzpicture}",
        r"\caption{Association-mapped (lazy) and identifier-referenced (byid) N+1 are "
        r"indistinguishable at nominal RTT $300\,\mu$s: they emit identical SQL, so the mapping "
        r"layer is invisible by construction. Cost is governed by the query pattern, not the "
        r"mapping philosophy.}",
        r"\label{fig:overlap}\end{figure}", ""]

    # --- Fig 3: H2a linearity, p50 vs measured distinct references ---
    for st in ("lazy", "byid"):
        for rtt in (0, 300):
            rs = []
            for n in NS:
                c = judge.get(agg, "b", st, rtt, n)
                if c and c["valid"] and not c["high_var"] and c["p50"] is not None:
                    rs.append((DBN.get(n, n), c["p50"]))
            write_dat(f"h2a-{st}-rtt{rtt}.dat", f"distinct_refs p50_ms ({st}, rtt{rtt})", rs)
    tex += [
        r"\begin{figure}[t]\centering",
        r"\begin{tikzpicture}\begin{axis}[width=\columnwidth,height=5cm,",
        r"  xlabel={Measured distinct references $D(N)$},ylabel={p50 latency (ms)},",
        r"  legend pos=north west,legend style={font=\footnotesize},grid=both]",
        r"\addplot table[x index=0,y index=1] {figures/h2a-lazy-rtt300.dat};\addlegendentry{lazy, RTT $300\,\mu$s}",
        r"\addplot table[x index=0,y index=1] {figures/h2a-byid-rtt300.dat};\addlegendentry{byid, RTT $300\,\mu$s}",
        r"\addplot table[x index=0,y index=1] {figures/h2a-lazy-rtt0.dat};\addlegendentry{lazy, RTT $0$}",
        r"\end{axis}\end{tikzpicture}",
        r"\caption{H2a: N+1 p50 is linear in the measured distinct-reference count $D(N)$ "
        r"($R^2 \ge 0.998$). At RTT $300\,\mu$s the slope is $\approx 1$ empirical round-trip per "
        r"distinct reference, the canonical N+1 signature.}",
        r"\label{fig:h2a}\end{figure}", ""]

    # --- Fig 4: cost-model intercepts a_style (ORM overhead = JDBC vs JPA gap) ---
    cm = judge.fit_cost_model(agg)
    pairs = [("join", "jdbc-join"), ("inbatch", "jdbc-inbatch"), ("seq", "jdbc-seq")]
    rows4 = []
    for i, (jpa, jdbc) in enumerate(pairs):
        a_jpa = cm["a_style"].get(jpa); a_jdbc = cm["a_style"].get(jdbc)
        if a_jpa is not None and a_jdbc is not None:
            rows4.append((i, jpa.replace("jdbc-", ""), a_jdbc, a_jpa))
    write_dat("orm-intercept.dat", "idx label a_jdbc_ms a_jpa_ms", rows4)
    tex += [
        r"\begin{figure}[t]\centering",
        r"\begin{tikzpicture}\begin{axis}[width=\columnwidth,height=5cm,ybar,",
        r"  symbolic x coords={join,inbatch,seq},xtick=data,",
        r"  ylabel={Zero-RTT intercept $a$ (ms)},legend pos=north west,",
        r"  legend style={font=\footnotesize},bar width=8pt]",
        r"\addplot coordinates {" + " ".join(f"({r[1]},{r[2]:.2f})" for r in rows4) + r"};\addlegendentry{JDBC}",
        r"\addplot coordinates {" + " ".join(f"({r[1]},{r[3]:.2f})" for r in rows4) + r"};\addlegendentry{JPA}",
        r"\end{axis}\end{tikzpicture}",
        r"\caption{Zero-RTT cost-model intercept $a_{\mathrm{style}}$ per query pattern: the "
        r"JPA-over-JDBC gap ($\approx 3$--$4$\,ms) is the constant ORM-infrastructure overhead; "
        r"it grows further with RTT (H7).}",
        r"\label{fig:orm}\end{figure}", ""]

    with open(os.path.join(OUT, "figures.tex"), "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"wrote {OUT}/figures.tex + {len([n for n in os.listdir(OUT) if n.endswith('.dat')])} .dat files")


if __name__ == "__main__":
    main()
